---
title: "LMTP_Data_Struct"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{LMTP_Data_Struct}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(modulatR)

n_units <- 100    # number of study units
n_timepoints <- 4 # number of time points

# Baseline covariates
baseline_df <- tibble(
  id = 1:n_units,
  W1 = rnorm(n_units, mean = 50, sd = 10),
  W2 = rbinom(n_units, size = 1, prob = 0.5)
)

# Expand to long format
longitudinal_data <- baseline_df %>%
  tidyr::expand_grid(time = 1:n_timepoints) %>%
  mutate(
    # Time-varying covariates
    L1 = rnorm(n(), mean = W1 / 10 + time, sd = 1),
    L2 = rbinom(n(), size = 1, prob = plogis(W1/100 + time/4)),
    
    # Exposure depends on past baseline + covariates
    A = rbinom(n(), size = 1, prob = plogis(-1 + 0.05 * W1 + 0.5 * L1 - 0.3 * time))
  )

# Final outcome based on baseline + last covariates and exposure
final_L1 <- longitudinal_data %>%
  filter(time == n_timepoints) %>%
  mutate(
    Y = rbinom(n(), size = 1, prob = plogis(0.1 * W1 - 0.2 * L1 + 0.3 * A))
  ) %>%
  select(id, Y)

# Merge back
longitudinal_data <- longitudinal_data %>%
  left_join(final_L1, by = "id")

# Peek
head(longitudinal_data)
```
